import type { Gem, GemId, Metal, MetalId, Ring } from "./types";

export const METALS: Record<MetalId, Metal> = {
  "yellow-gold": {
    id: "yellow-gold",
    label: "18K Yellow Gold",
    color: "#f2c14e",
    roughness: 0.17,
    swatch: ["#f7dd9a", "#c99a2e"],
  },
  "rose-gold": {
    id: "rose-gold",
    label: "18K Rose Gold",
    color: "#e0a08a",
    roughness: 0.19,
    swatch: ["#f4c3ae", "#b9705a"],
  },
  "white-gold": {
    id: "white-gold",
    label: "18K White Gold",
    color: "#e8e9ec",
    roughness: 0.12,
    swatch: ["#fbfbfc", "#b9bcc4"],
  },
  platinum: {
    id: "platinum",
    label: "950 Platinum",
    color: "#dcdde1",
    roughness: 0.22,
    swatch: ["#f2f3f5", "#a9adb6"],
  },
};

export const GEMS: Record<GemId, Gem> = {
  diamond: {
    id: "diamond",
    label: "Diamond",
    color: "#ffffff",
    ior: 2.42,
    transmission: 1,
    dispersion: 3.2,
    roughness: 0,
  },
  ruby: {
    id: "ruby",
    label: "Ruby",
    color: "#c2183c",
    ior: 1.77,
    transmission: 0.92,
    dispersion: 0.9,
    roughness: 0.02,
  },
  sapphire: {
    id: "sapphire",
    label: "Blue Sapphire",
    color: "#1c4fa8",
    ior: 1.77,
    transmission: 0.9,
    dispersion: 0.9,
    roughness: 0.02,
  },
  emerald: {
    id: "emerald",
    label: "Emerald",
    color: "#1f7a4d",
    ior: 1.58,
    transmission: 0.85,
    dispersion: 0.7,
    roughness: 0.05,
  },
  amethyst: {
    id: "amethyst",
    label: "Amethyst",
    color: "#7b4bb7",
    ior: 1.54,
    transmission: 0.9,
    dispersion: 0.6,
    roughness: 0.03,
  },
  aquamarine: {
    id: "aquamarine",
    label: "Aquamarine",
    // A pale, faintly green-leaning blue — the beryl in the reference pendant,
    // not the deeper blue of a topaz.
    color: "#a8ccd6",
    ior: 1.577,
    transmission: 0.94,
    dispersion: 0.5,
    roughness: 0.02,
  },
  onyx: {
    id: "onyx",
    label: "Black Onyx",
    color: "#14151a",
    ior: 1.49,
    transmission: 0,
    dispersion: 0,
    roughness: 0.08,
  },
};

export const METAL_ORDER: MetalId[] = [
  "yellow-gold",
  "rose-gold",
  "white-gold",
  "platinum",
];

export const RINGS: Ring[] = [
  {
    id: "camellia-bloom",
    name: "Camellia Bloom",
    collection: "Floral",
    description:
      "Six sandblasted petals cast around a claw-set brilliant, each edge finished with a polished rim so the flower catches light at its folds rather than across its face. The shank tapers into the head so the join reads as a stem.",
    metals: ["yellow-gold", "rose-gold", "white-gold"],
    gem: "diamond",
    carat: 0.25,
    bestseller: true,
    tags: ["floral", "statement", "diamond"],
    design: {
      bandInnerScale: 1.0,
      bandThickness: 0.2,
      bandWidth: 0.3,
      profile: "comfort",
      setting: "floral",
      gemSize: 0.19,
      gemCut: "round",
      accentCount: 6,
      floral: {
        petals: 6,
        headRadius: 0.92,
        gemRadius: 0.19,
        scallop: 0.42,
        cup: 0.38,
      },
    },
  },
  {
    id: "wild-rose",
    name: "Wild Rose",
    collection: "Floral",
    description:
      "A looser, five-petal version with deeper scalloping and a wider cup. Reads larger on the hand than the Camellia despite carrying a smaller stone.",
    metals: ["rose-gold", "yellow-gold", "white-gold"],
    gem: "diamond",
    carat: 0.18,
    tags: ["floral", "everyday", "diamond"],
    design: {
      bandInnerScale: 1.0,
      bandThickness: 0.19,
      bandWidth: 0.28,
      profile: "comfort",
      setting: "floral",
      gemSize: 0.16,
      gemCut: "round",
      accentCount: 6,
      floral: {
        petals: 5,
        headRadius: 1.02,
        gemRadius: 0.16,
        scallop: 0.62,
        cup: 0.46,
      },
    },
  },
  {
    id: "aurora-solitaire",
    name: "Aurora Solitaire",
    collection: "Bridal",
    description:
      "A single brilliant-cut diamond lifted on six tapered claws so light reaches the pavilion from every side. The shank narrows toward the setting to make the stone read a half size larger than it is.",
    metals: ["yellow-gold", "rose-gold", "white-gold", "platinum"],
    gem: "diamond",
    carat: 0.9,
    bestseller: true,
    tags: ["engagement", "classic", "diamond"],
    design: {
      bandInnerScale: 1.0,
      bandThickness: 0.21,
      bandWidth: 0.31,
      profile: "comfort",
      setting: "solitaire",
      gemSize: 0.5,
      gemCut: "round",
      accentCount: 6,
    },
  },
  {
    id: "celeste-halo",
    name: "Celeste Halo",
    collection: "Bridal",
    description:
      "A round centre stone ringed by eighteen pavé accents. The halo catches ambient light even indoors, which is what gives this style its outsized presence on the hand.",
    metals: ["white-gold", "platinum", "yellow-gold"],
    gem: "diamond",
    carat: 1.2,
    bestseller: true,
    tags: ["engagement", "statement", "diamond"],
    design: {
      bandInnerScale: 1.0,
      bandThickness: 0.2,
      bandWidth: 0.3,
      profile: "flat",
      setting: "halo",
      gemSize: 0.44,
      gemCut: "round",
      accentCount: 18,
    },
  },
  {
    id: "vera-emerald",
    name: "Vera Emerald Cut",
    collection: "Bridal",
    description:
      "Step facets instead of brilliant ones, so the stone flashes in broad planes rather than sparkles. Set east-west on a knife-edge shank for a deliberately architectural line.",
    metals: ["platinum", "white-gold", "yellow-gold"],
    gem: "diamond",
    carat: 1.5,
    tags: ["engagement", "modern", "diamond"],
    design: {
      bandInnerScale: 1.0,
      bandThickness: 0.18,
      bandWidth: 0.26,
      profile: "knife",
      setting: "solitaire",
      gemSize: 0.52,
      gemCut: "emerald",
      accentCount: 4,
    },
  },
  {
    id: "scarlet-trilogy",
    name: "Scarlet Trilogy",
    collection: "Heritage",
    description:
      "A Burmese ruby flanked by two tapered diamonds. Three-stone rings read as past, present and future, and the warm centre keeps the whole piece from feeling austere.",
    metals: ["yellow-gold", "rose-gold", "white-gold"],
    gem: "ruby",
    carat: 1.1,
    tags: ["heritage", "colour", "ruby"],
    design: {
      bandInnerScale: 1.0,
      bandThickness: 0.21,
      bandWidth: 0.31,
      profile: "comfort",
      setting: "three-stone",
      gemSize: 0.42,
      gemCut: "oval",
      accentCount: 2,
    },
  },
  {
    id: "indigo-royale",
    name: "Indigo Royale",
    collection: "Heritage",
    description:
      "A cushion sapphire in a milgrain-edged setting with a pavé shoulder line. Deliberately a period piece — the proportions are drawn from Edwardian originals.",
    metals: ["white-gold", "platinum", "yellow-gold"],
    gem: "sapphire",
    carat: 1.4,
    bestseller: true,
    tags: ["heritage", "colour", "sapphire"],
    design: {
      bandInnerScale: 1.0,
      bandThickness: 0.23,
      bandWidth: 0.35,
      profile: "flat",
      setting: "halo",
      gemSize: 0.46,
      gemCut: "princess",
      accentCount: 14,
    },
  },
  {
    id: "verdant-pear",
    name: "Verdant Pear",
    collection: "Colour",
    description:
      "A pear-cut Zambian emerald set point-to-finger. Emerald is softer than corundum, so the claws sit low and the girdle is protected by the setting rather than exposed.",
    metals: ["yellow-gold", "white-gold", "platinum"],
    gem: "emerald",
    carat: 1.3,
    tags: ["colour", "statement", "emerald"],
    design: {
      bandInnerScale: 1.0,
      bandThickness: 0.19,
      bandWidth: 0.29,
      profile: "comfort",
      setting: "solitaire",
      gemSize: 0.5,
      gemCut: "pear",
      accentCount: 4,
    },
  },
  {
    id: "luna-marquise",
    name: "Luna Marquise",
    collection: "Colour",
    description:
      "An elongated marquise amethyst that visually lengthens the finger. The long axis follows the bone rather than sitting across it, which is why it flatters shorter hands.",
    metals: ["rose-gold", "yellow-gold", "white-gold"],
    gem: "amethyst",
    carat: 1.6,
    tags: ["colour", "everyday", "amethyst"],
    design: {
      bandInnerScale: 1.0,
      bandThickness: 0.17,
      bandWidth: 0.26,
      profile: "knife",
      setting: "solitaire",
      gemSize: 0.54,
      gemCut: "marquise",
      accentCount: 4,
    },
  },
  {
    id: "eternal-pave",
    name: "Eternal Pavé",
    collection: "Everyday",
    description:
      "Forty round accents channel-set the full circumference. A true eternity band cannot be resized, so measure carefully — the size guide takes about a minute.",
    metals: ["white-gold", "platinum", "yellow-gold", "rose-gold"],
    gem: "diamond",
    carat: 0.8,
    tags: ["wedding", "everyday", "diamond"],
    design: {
      bandInnerScale: 1.0,
      bandThickness: 0.23,
      bandWidth: 0.32,
      profile: "flat",
      setting: "eternity",
      gemSize: 0,
      gemCut: "round",
      accentCount: 40,
    },
  },
  {
    id: "meridian-band",
    name: "Meridian Band",
    collection: "Everyday",
    description:
      "A plain comfort-fit band with a rounded interior, 4 mm across. The one ring on this list you can genuinely forget you are wearing.",
    metals: ["yellow-gold", "rose-gold", "white-gold", "platinum"],
    gem: "onyx",
    tags: ["wedding", "everyday", "minimal"],
    design: {
      bandInnerScale: 1.0,
      bandThickness: 0.25,
      bandWidth: 0.48,
      profile: "comfort",
      setting: "plain",
      gemSize: 0,
      gemCut: "round",
      accentCount: 0,
    },
  },
  {
    id: "helix-twist",
    name: "Helix Twist",
    collection: "Everyday",
    description:
      "Two shanks wound around each other with pavé running the length of one strand. The twist means it never quite sits the same way twice, which is rather the point.",
    metals: ["rose-gold", "yellow-gold", "white-gold"],
    gem: "diamond",
    tags: ["everyday", "modern", "diamond"],
    design: {
      bandInnerScale: 1.0,
      bandThickness: 0.19,
      bandWidth: 0.42,
      profile: "twist",
      setting: "pave",
      gemSize: 0,
      gemCut: "round",
      accentCount: 22,
    },
  },
  {
    id: "onyx-signet",
    name: "Onyx Signet",
    collection: "Modern",
    description:
      "A flat oval of black onyx inlaid into a broad shank. Unisex, deliberately heavy, and the only piece here designed to be worn on the little finger.",
    metals: ["yellow-gold", "white-gold", "platinum"],
    gem: "onyx",
    tags: ["modern", "unisex", "signet"],
    design: {
      bandInnerScale: 1.0,
      bandThickness: 0.27,
      bandWidth: 0.54,
      profile: "flat",
      setting: "solitaire",
      gemSize: 0.58,
      gemCut: "oval",
      accentCount: 0,
    },
  },
  {
    id: "nova-tension",
    name: "Nova Tension",
    collection: "Modern",
    description:
      "The stone is held by the compression of the shank alone, with no claws touching the crown. It requires a harder metal, so this one is platinum-first.",
    metals: ["platinum", "white-gold"],
    gem: "diamond",
    carat: 1.0,
    tags: ["modern", "statement", "diamond"],
    design: {
      bandInnerScale: 1.0,
      bandThickness: 0.25,
      bandWidth: 0.25,
      profile: "knife",
      setting: "solitaire",
      gemSize: 0.48,
      gemCut: "round",
      accentCount: 2,
    },
  },
];

export const COLLECTIONS = [
  "Floral",
  "Bridal",
  "Heritage",
  "Colour",
  "Everyday",
  "Modern",
] as const;

export function getRing(id: string): Ring | undefined {
  return RINGS.find((r) => r.id === id);
}


